//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.Science.FetchClimate2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airt")]
        public string FC_TEMPERATURE {
            get {
                return ((string)(this["FC_TEMPERATURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airt_land")]
        public string FC_LAND_AIR_TEMPERATURE {
            get {
                return ((string)(this["FC_LAND_AIR_TEMPERATURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elev")]
        public string FC_ELEVATION {
            get {
                return ((string)(this["FC_ELEVATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elev_land")]
        public string FC_LAND_ELEVATION {
            get {
                return ((string)(this["FC_LAND_ELEVATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("soilmoist")]
        public string FC_SOIL_MOISTURE {
            get {
                return ((string)(this["FC_SOIL_MOISTURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("relhum")]
        public string FC_RELATIVE_HUMIDITY {
            get {
                return ((string)(this["FC_RELATIVE_HUMIDITY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("relhum_land")]
        public string FC_LAND_AIR_RELATIVE_HUMIDITY {
            get {
                return ((string)(this["FC_LAND_AIR_RELATIVE_HUMIDITY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windspeed")]
        public string FC_LAND_WIND_SPEED {
            get {
                return ((string)(this["FC_LAND_WIND_SPEED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dtr")]
        public string FC_LAND_DIURNAL_TEMPERATURE_RANGE {
            get {
                return ((string)(this["FC_LAND_DIURNAL_TEMPERATURE_RANGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("frs")]
        public string FC_LAND_FROST_DAY_FREQUENCY {
            get {
                return ((string)(this["FC_LAND_FROST_DAY_FREQUENCY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wet")]
        public string FC_LAND_WET_DAY_FREQUENCY {
            get {
                return ((string)(this["FC_LAND_WET_DAY_FREQUENCY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sunp")]
        public string FC_LAND_SUN_PERCENTAGE {
            get {
                return ((string)(this["FC_LAND_SUN_PERCENTAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prate")]
        public string FC_PRECIPITATION {
            get {
                return ((string)(this["FC_PRECIPITATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CRU CL 2.0")]
        public string CRU_CL_2_0 {
            get {
                return ((string)(this["CRU_CL_2_0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NCEP/NCAR Reanalysis 1 (regular grid)|NCEP/NCAR Reanalysis 1 (Gauss T62)")]
        public string NCEP_REANALYSIS_1 {
            get {
                return ((string)(this["NCEP_REANALYSIS_1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GHCNv2")]
        public string GHCNv2 {
            get {
                return ((string)(this["GHCNv2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CpcSoilMoisture")]
        public string CPC_SOIL_MOSITURE {
            get {
                return ((string)(this["CPC_SOIL_MOSITURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ETOPO1")]
        public string ETOPO1_ICE_SHEETS {
            get {
                return ((string)(this["ETOPO1_ICE_SHEETS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GTOPO30")]
        public string GTOPO30 {
            get {
                return ((string)(this["GTOPO30"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorldClim 1.4")]
        public string WORLD_CLIM_1_4 {
            get {
                return ((string)(this["WORLD_CLIM_1_4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fetchclimate2.cloudapp.net")]
        public string ServiceUrl {
            get {
                return ((string)(this["ServiceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("depth_ocean")]
        public string FC_OCEAN_DEPTH {
            get {
                return ((string)(this["FC_OCEAN_DEPTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("airt_ocean")]
        public string FC_OCEAN_AIR_TEMPERATURE {
            get {
                return ((string)(this["FC_OCEAN_AIR_TEMPERATURE"]));
            }
        }
    }
}
